# name: Baidu EFE
# url: http://efe.baidu.com
source:      .
destination: ./_site
plugins:     ./_plugins
lsi:      false
safe:     false
markdown: kramdown
highlighter: pygments
permalink: /:title
paginate: 12
paginate_path: "articles/page:num"
encoding: utf-8

post_defaults:
  layout: post

# redcarpet:
#   extensions: ["tables", "autolink", "footnotes"]

kramdown:
  input: GFM
  use_coderay: true
