# name: Baidu EFE
# url: http://efe.baidu.com
source:      .
destination: ./_site
plugins:     ./_plugins
lsi:      false
safe:     false
pygments: true
markdown: kramdown
permalink: /:year/:month/:title
paginate: 12
paginate_path: "articles/page:num"
encoding: utf-8

post_defaults:
  layout: post

redcarpet:
  extensions: ["tables", "autolink"]
